name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t score-predictor .

      - name: Stop old container
        run: docker stop score-predictor || true

      - name: Remove old container
        run: docker rm score-predictor || true

      - name: Run new container
        run: |
          docker run -d \
            --name score-predictor \
            -p 8080:8080 \
            --restart unless-stopped \
            score-predictor
